USE [master]
GO

/****** Object:  Database [QLPMT]    Script Date: 19-Apr-21 9:09:11 PM ******/
CREATE DATABASE [QLPMT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLPMT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QLPMT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLPMT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QLPMT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLPMT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLPMT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLPMT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLPMT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLPMT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLPMT] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLPMT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLPMT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLPMT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLPMT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLPMT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLPMT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLPMT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLPMT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLPMT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLPMT] SET  ENABLE_BROKER 
GO

ALTER DATABASE [QLPMT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLPMT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLPMT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLPMT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLPMT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLPMT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLPMT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLPMT] SET RECOVERY FULL 
GO

ALTER DATABASE [QLPMT] SET  MULTI_USER 
GO

ALTER DATABASE [QLPMT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLPMT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLPMT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLPMT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLPMT] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLPMT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QLPMT] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QLPMT] SET  READ_WRITE 
GO


